branch-defaults:
  mt/pipenv2:
    environment: Tabbycat-39
environment-defaults:
  tabbycat-calico:
    branch: null
    repository: null
global:
  application_name: tabbycat
  default_ec2_keyname: null
  default_platform: Python 3.9 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
