# Generated by Django 3.1.1 on 2021-09-19 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='managers'),
        ),
        migrations.RunSQL(
            "INSERT INTO registration_tournament_managers (tournament_id, user_id) SELECT id, manager_id FROM registration_tournament;",
            migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='manager',
        ),
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'United States Dollar')], max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'United States Dollar')], max_length=3, verbose_name='currency'),
        ),
    ]
