# Generated by Django 3.1.1 on 2021-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210918_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicator',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='external URL'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='external URL'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='requested_adjudicators',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='adjudicators requested'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='requested_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='teams requested'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='adjudicators_paid',
            field=models.ManyToManyField(blank=True, to='registration.Adjudicator', verbose_name='adjudicators paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='paid on'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='teams_paid',
            field=models.ManyToManyField(blank=True, to='registration.Team', verbose_name='teams paid'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='external URL'),
        ),
    ]
