# Generated by Django 3.1.1 on 2021-10-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210924_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.institution', verbose_name='institution'),
        ),
    ]
