# Generated by Django 4.1.1 on 2022-10-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20211011_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAApplicant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.person')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'IA applicant',
                'verbose_name_plural': 'IA applicants',
            },
            bases=('registration.person',),
        ),
        migrations.CreateModel(
            name='IATournamentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('priority', models.CharField(max_length=2, verbose_name='priority')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'IA tournament category',
                'verbose_name_plural': 'IA tournament categories',
            },
        ),
        migrations.CreateModel(
            name='IATournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('year', models.PositiveIntegerField(blank=True, verbose_name='year')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('', 'Otro')], max_length=3, verbose_name='language')),
                ('role', models.CharField(choices=[('a', 'jueza'), ('c', 'adjudication core'), ('s', 'speaker')], max_length=1, verbose_name='participant role')),
                ('not_bp', models.BooleanField(blank=True, verbose_name='is not BP')),
                ('rooms', models.PositiveIntegerField(blank=True, verbose_name='number of rooms')),
                ('last_round', models.CharField(blank=True, max_length=20, verbose_name='last round as participant')),
                ('last_round_chair', models.CharField(blank=True, max_length=20, null=True, verbose_name='last round as chair')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.iaapplicant', verbose_name='application')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.iatournamentcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'IA tournament',
                'verbose_name_plural': 'IA tournaments',
            },
        ),
    ]
