# Generated by Django 3.2 on 2021-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_client_timezone_squashed_0003_auto_20201017_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='end_date',
            field=models.DateField(help_text="The end date of the site's event. Tournament creation on the site will be disabled afterwards.", null=True, verbose_name='end date'),
        ),
    ]
