# Generated by Django 3.1.1 on 2021-09-19 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210906_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='number_tournaments',
            field=models.PositiveIntegerField(default=1, verbose_name='number of tournaments'),
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('r', 'Regular'), ('p', 'Pro')], default='r', max_length=1, verbose_name='plan'),
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Label to easily identify wanted backup, eg. 'After R1'", max_length=50, verbose_name='name')),
                ('filename', models.CharField(max_length=100, verbose_name='filename')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user_initiated', models.BooleanField(default=False, verbose_name='user-initiated')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
            },
        ),
    ]
