# Generated by Django 3.1.1 on 2021-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210919_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('aud', 'Australian Dollar'), ('cad', 'Canadian Dollar'), ('eur', 'European Euro'), ('usd', 'United States Dollar')], default='cad', help_text='Calico supports payment in various currencies to avoid conversion fees.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='client',
            name='end_date',
            field=models.DateField(blank=True, help_text="The end date of the site's event. Tournament creation on the site will be disabled afterwards.", null=True, verbose_name='end date'),
        ),
    ]
